name: Build Android APK

on:
  push:
    branches:
      - main
    paths:
      - 'mobile/**'
  workflow_dispatch: # Allows you to manually trigger the build from the Actions tab

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        working-directory: ./mobile
        run: npm ci

      - name: Generate Native Android Directory (Prebuild)
        working-directory: ./mobile
        run: npx expo prebuild --platform android

      - name: Build Android Release APK
        working-directory: ./mobile/android
        run: ./gradlew assembleRelease

      - name: Upload APK as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: mobile/android/app/build/outputs/apk/release/app-release.apk
          retention-days: 7
